apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: smcp-2
  namespace: smcp-2-lab-ossm-apim
spec:
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
    sampling: 10000
    type: Jaeger
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.1
  telemetry:
    type: Istiod