apiVersion: federation.maistra.io/v1
kind: ServiceMeshPeer
metadata:
  name: mesh2
  namespace: smcp-1-lab-ossm-apim
spec:
  remote:
    addresses:
    - {{MESH2_ADDRESS}}
    discoveryPort: {{MESH2_DISCOVERY_PORT}}
    servicePort: {{MESH2_SERVICE_PORT}}
  gateways:
    ingress:
      name: mesh2-ingress
    egress:
      name: mesh2-egress
  security:
    trustDomain: mesh2.local
    clientID: mesh2.local/ns/smcp-2-lab-ossm-apim/sa/mesh1-egress-service-account
    # same as default, if certificateChain is omitted
    certificateChain:
      kind: ConfigMap
      name: mesh2-ca-root-cert