apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: true
      secureJsonData:
        httpHeaderValue1: >-
          Bearer
          <ACCESS TOKEN>
      name: Prometheus
      url: >-
        https://thanos-querier-openshift-monitoring.<OCP APPLICATIONS DOMAIN>
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
      isDefault: true
      version: 1
      type: prometheus
  name: middleware
status:
  message: ''
  phase: ''
