apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-lab-ossm-apim
spec:
  wildcardDomain: apps.cluster-gkflx.gkflx.sandbox1686.opentlc.com
  resourceRequirementsEnabled: true