# Reference: https://github.com/3scale/3scale-operator/blob/3scale-2.12.0-GA/doc/apimanager-reference.md
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
spec:
  wildcardDomain: apps.cluster-b98jt.b98jt.sandbox88.opentlc.com
  appLabel: 3scale-api-management
  tenantName: apim-demo
  imagePullSecrets:
    - name: threescale-registry-auth
  # Resource requirements distabled for DEMO purposes
  resourceRequirementsEnabled: false
  apicast:
    managementAPI: status
    openSSLVerify: false
    responseCodes: true
    productionSpec:
      replicas: 3
      logLevel: info
      # OpenTracing configuration
      openTracing:
        # Controls whether OpenTracing integration with APIcast is enabled - default: false
        enabled: true
        # Controls which OpenTracing library is loaded. At the moment the supported values are: jaeger. 
        # If not set, jaeger will be used
        tracingLibrary: jaeger
        # Secret reference with the tracing library-specific configuration. 
        # Each supported tracing library provides a default configuration file which is used if tracingConfigSecretRef 
        # is not specified
        tracingConfigSecretRef: 
          name: threescale-production-jaeger-conf-secret
      # Configures anti-affinity strategies that guarantee the Production APIcast availability.
      # Here: prefers multiple zones when scheduling pods but schedules the Production APIcast replica pods on 
      # different OpenShift nodes if it is not possible to schedule across zones 
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: 3scale-api-management
                  deploymentConfig: apicast-production
                  threescale_component: apicast
                  threescale_component_element: production
              topologyKey: "topology.kubernetes.io/zone"
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: 3scale-api-management
                  deploymentConfig: apicast-production
                  threescale_component: apicast
                  threescale_component_element: production
              topologyKey: "kubernetes.io/hostname"
    stagingSpec:
      replicas: 1
      logLevel: info
      # OpenTracing configuration
      openTracing:
        # Controls whether OpenTracing integration with APIcast is enabled - default: false
        enabled: true
        # Controls which OpenTracing library is loaded. At the moment the supported values are: jaeger. 
        # If not set, jaeger will be used
        tracingLibrary: jaeger
        # Secret reference with the tracing library-specific configuration. 
        # Each supported tracing library provides a default configuration file which is used if tracingConfigSecretRef 
        # is not specified
        tracingConfigSecretRef: 
          name: threescale-staging-jaeger-conf-secret
  backend:
    listenerSpec:
      replicas: 3
      # Configures anti-affinity strategies that guarantee the Backend Listener availability.
      # Here: prefers multiple zones when scheduling pods but schedules the Backend Listener replica pods on 
      # different OpenShift nodes if it is not possible to schedule across zones 
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: 3scale-api-management
                  deploymentConfig: backend-listener
                  threescale_component: backend
                  threescale_component_element: listener
              topologyKey: "topology.kubernetes.io/zone"
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: 3scale-api-management
                  deploymentConfig: backend-listener
                  threescale_component: backend
                  threescale_component_element: listener
              topologyKey: "kubernetes.io/hostname"
    workerSpec:
      replicas: 3
      # Configures anti-affinity strategies that guarantee the Backend Worker availability.
      # Here: prefers multiple zones when scheduling pods but schedules the Backend Worker replica pods on 
      # different OpenShift nodes if it is not possible to schedule across zones 
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: 3scale-api-management
                  deploymentConfig: backend-worker
                  threescale_component: backend
                  threescale_component_element: worker
              topologyKey: "topology.kubernetes.io/zone"
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: 3scale-api-management
                  deploymentConfig: backend-worker
                  threescale_component: backend
                  threescale_component_element: worker
              topologyKey: "kubernetes.io/hostname"
    cronSpec:
      replicas: 1
  system:
    fileStorage:
      # Use S3 as the System's file storage
      simpleStorageService:
        # Local object reference to the secret to be used where the AWS configuration is stored
        configurationSecretRef:
          name: 3scale-aws-s3-auth-secret
    appSpec:
      replicas: 2
    sidekiqSpec:
      replicas: 2
  zync:
    appSpec:
      replicas: 1
    queSpec:
      replicas: 1
  # /!\ External databases mode expects to have pre-created secrets with the desired database URL.
  externalComponents:
    backend:
      redis: true
    system:
      database: true
      redis: true
    zync:
      database: true
    # # Enable to use external system database, backend redis, and system redis databases
    # enabled: true
    # # Enable to use external zync database. 
    # # The value of this field only takes effect when spec.highAvailability.enabled is set to true
    # externalZyncDatabaseEnabled: false
  podDisruptionBudget:
    # Enable to automatically create PodDisruptionBudgets for components that can scale. 
    # Not including any of the databases or redis services.
    enabled: true
  monitoring:
    # Enable to automatically create monitoring resources
    enabled: true
    # Activate/Disable PrometheusRules deployment
    # Default: true
    enablePrometheusRules: true