apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: reviews-mtls
spec:
  selector:
    matchLabels:
      app: reviews
  mtls:
    mode: STRICT
---
# By default OSSM enables mtls in permissive mode
#apiVersion: security.istio.io/v1beta1
#kind: PeerAuthentication
#metadata:
#  name: disable-mtls
#spec:
#  mtls:
#    mode: DISABLE
