apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apim-install
  namespace: gitops-lab-ossm-apim
  labels:
    project: lab-ossm-apim
spec:
  destination:
    name: in-cluster
    namespace: 3scale-lab-ossm-apim
  project: lab-ossm-apim
  source:
    path: APIM/INSTALL
    repoURL: 'https://github.com/saberkan/lab-ossm-apim.git'