apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: gitops-lab-ossm-apim
  labels:
    project: lab-ossm-apim
spec:
  destination:
    name: in-cluster
    namespace: bookinfo-lab-ossm-apim
  project: lab-ossm-apim
  source:
    path: SERVICE_MESH/APPLICATION/BOOKINFO
    repoURL: 'https://github.com/saberkan/lab-ossm-apim.git'