apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab-ossm-apim
  namespace: gitops-lab-ossm-apim
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'