apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smcp-2
  namespace: gitops-lab-ossm-apim
  labels:
    project: lab-ossm-apim
spec:
  destination:
    name: in-cluster
  project: lab-ossm-apim
  source:
    path: SERVICE_MESH/MANIFESTS/mesh-2
    repoURL: 'https://github.com/saberkan/lab-ossm-apim.git'